models:
 - type: main
   engine: openai
   model: gpt-3.5-turbo

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the UCSD Mental Health Bot.
      The bot is designed to answer student questions about UCSD events as well as direct students to resources.

rails:
  input:
    flows:
      - self check input
    force_flow_response: True
    fallback_to_llm: False
  output:
    force_flow_response: True
  dialog:
    user_messages:
      embeddings_only: True
      embeddings_only_similarity_threshold: 0.75
    single_call:
      enabled: False
      fallback_to_multiple_calls: False
  
prompts:
  - task: self_check_facts
    content: |-
      You are given a task to identify if the hypothesis is grounded and entailed to the evidence.
      You will only use the contents of the evidence and not rely on external knowledge.
      Answer with yes/no. "evidence": {{ evidence }} "hypothesis": {{ response }} "entails":

