models:
 - type: main
   engine: openai
   model: gpt-3.5-turbo

instructions:
  - type: general
    content: |
      Below is a conversation between a user and a bot called the UCSD Mental Health Bot.
      The bot is designed to answer student questions about UCSD events as well as direct students to resources.

rails:
  input:
    flows:
      - self check input
  dialog:
    user_messages:
      embeddings_only: True
      embeddings_only_similarity_threshold: 0.75
    single_call:
      enabled: False
      fallback_to_multiple_calls: False

